#define BEGININDEX 0
#define ENDINDEX 100
#define TIMERANGE (ENDINDEX-BEGININDEX)
#define TIMEGAP 10
#define KEYFRAMENUM (TIMERANGE/TIMEGAP)
#define rasterWidth 2048
#define rasterHeight 2048
#define windowWidth 1024
#define windowHeight 1024